// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkxrcqwaymdtljgoostc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhreHJjcXdheW1kdGxqZ29vc3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1NTY1NzEsImV4cCI6MjA1NDEzMjU3MX0.q_meJ6u-i21hoCZhu1TrV7l7o5ZOzUuwcEev9HOZqkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);